SOURCE_FILES  = main.c AIStrategy.c checkboard.c player.c  util.c evaluate_point.c
default:
	cc -g3 -std=c99 $(SOURCE_FILES) -o gobang
two :
	cc -g3 -std=c99 $(SOURCE_FILES) -DTWOUSERS -o two
first :
	cc -g3 -std=c99 $(SOURCE_FILES) -DFIRST -o first
